bq-dbt-workshop:
  outputs:
    dev:
      dataset: <bigquery-dataset>
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: <gcp-project-id>
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
